### PR TITLE
add volume control to pipeline

### PR DESCRIPTION
**Pull request by itsb**
Addresses #2.

### CODE REVIEW

**Comment by gmsoft-tuxicoman** [comment]
Thanks for your patch. Wouldn't it be best to change the volume porperty of the sink instead of changing the volume of the audio ?

Moreover, there are scenario where you don't want volume control if it's handled separately. For example I use a script that uses the volume properties and sends the right serial commands to my sound system. Please add an option in the arguments to disable it.

**Comment by itsb** [comment]
The alsa sink currently in use does not seem to expose volume control, see [docs](https://gstreamer.freedesktop.org/documentation/alsa/alsasink.html?gi-language=python). That said, I was able to use sink volume control with the pulse audio sink added in [this fork](https://github.com/hubearth/bt-audio), see [pulsesink docs](https://gstreamer.freedesktop.org/documentation/pulseaudio/pulsesink.html?gi-language=python).
Please let me know how you want to proceed. Should we merge the pulseaudio toggle first and then add the volume toggle?

**Comment by gmsoft-tuxicoman** [comment]
Sure pulse audio toggle works for me. We can commit that first. However pulse audio already has support for BT and volume support, make sure they don't interfere.

**Comment by itsb** [comment]
cherry-picked Hubert's `--pulse` toggle, and added my `--volcon` toggle on top

**Comment by gmsoft-tuxicoman** [comment]
Thanks !

**Pull request merged**
